source "https://rubygems.org"

gemspec name: "masks"

gem "railties", "~> 8.1"
gem "actionpack", "~> 8.1"
gem "actionview", "~> 8.1"
gem "rails-dom-testing", "~> 2.2"
gem "minitest", "~> 5.25"
gem "rake", "~> 13.2"

group :development do
  gem "sdoc", "~> 2.6"
  gem "rdoc", "~> 6.14"
end

group :test do
  gem "webmock", "~> 3.25"
end
