require "rake/testtask"

%w[client rails].each do |half|
  Rake::TestTask.new("test:#{half}") do |t|
    t.libs << "lib" << "test"
    t.test_files = FileList["test/#{half}/**/*_test.rb"]
    t.warning = false
  end
end

task test: %w[test:client test:rails]

task default: :test
