require "rails"

require_relative "version"
require_relative "client"
require_relative "rails/credentials"
require_relative "rails/configuration"
require_relative "rails/configurable"
require_relative "rails/authentication"
require_relative "rails/protected_resource"
require_relative "rails/engine"
