# Specify your actors here.
#
# Like other models, pass `local: true` to create synthetic, in-memory actors.
#
#  - https://masksrb.github.io/guides/rails
#  - https://masksrb.github.io/reference/providers#providersyml
#
# Note: ERB-templating is supported. Use ENV vars for sensitive data.
#
default: &default
  manager:
    manager: true
    nickname: manager
    email: manager@example.com
    password: <%= ENV['MASKS_MANAGER_PASSWORD'] %%>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
