# Customize your masks installation in this file.
#
# - https://masksrb.github.io/guides/rails
# - https://masksrb.github.io/reference/masks.yml
defaults: &defaults
  url: <%= ENV['MASKS_URL'] %>
  mode: server

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
