version: 2
updates:
  - package-ecosystem: bundler
    directories:
      - "/"
      - "/server"
      - "/client"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directories:
      - "/server"
      - "/web"
      - "/docs"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directories:
      - "/server"
      - "/conformance"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
