#!/usr/bin/env ruby
ENGINE_ROOT = File.expand_path(".", __dir__)
ENGINE_PATH = File.expand_path("./lib/masks/engine", __dir__)
APP_PATH = File.expand_path("./server/config/application", __dir__)

# Set up gems listed in the Gemfile.
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("./Gemfile", __dir__)
require "bundler/setup" if File.exist?(ENV["BUNDLE_GEMFILE"])

begin
  require "#{File.dirname(APP_PATH)}/environment"
rescue => e
  puts "Skipping Rails..."
end

require_relative "lib/masks/cli"
