source "https://rubygems.org"

gemspec name: "masks-rails"

gem "masks-client", path: "../client"

gem "railties", "~> 8.1"
gem "actionpack", "~> 8.1"
gem "actionview", "~> 8.1"
gem "rails-dom-testing", "~> 2.2"
gem "minitest", "~> 5.25"
gem "rake", "~> 13.2"
