default: &default
  cleanup:
    class: CleanupJob
    queue: maintenance
    schedule: every day at 4am

  authenticators:
    class: RefreshAuthenticatorsJob
    queue: maintenance
    schedule: every day at 3am

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
