default: &default
  cleanup:
    class: Masks::Server::CleanupJob
    queue: maintenance
    schedule: every day at 4am

  authenticators:
    class: Masks::Server::RefreshAuthenticatorsJob
    queue: maintenance
    schedule: every day at 3am

  saml_metadata:
    class: Masks::Server::RefreshSamlMetadataJob
    queue: maintenance
    schedule: every day at 2am

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
