# Customize your masks installation in this file.
#
# - https://masksrb.github.io/guides/rails
# - https://masksrb.github.io/reference/masks.yml
defaults: &defaults
  mode: server

development:
  url: http://localhost:5000
  <<: *defaults

test:
  url: http://www.example.com
  <<: *defaults

production:
  url: <%= ENV['MASKS_URL'] %>
  <<: *defaults
