# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=3.4.7
ARG NODE_VERSION=26.0.0

FROM docker.io/library/node:$NODE_VERSION-slim AS node

FROM docker.io/library/ruby:$RUBY_VERSION-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential curl git libjemalloc2 libpq-dev libvips42t64 libyaml-dev \
      pkg-config postgresql-client && \
    ln -s /usr/lib/$(uname -m)-linux-gnu/libjemalloc.so.2 /usr/local/lib/libjemalloc.so && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/lib/node_modules/npm /usr/local/lib/node_modules/npm
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm && \
    ln -s /usr/local/lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx

ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle" \
    LD_PRELOAD="/usr/local/lib/libjemalloc.so" \
    BINDING="0.0.0.0" \
    PORT="80"

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY --from=web . /web
RUN cd /web && npm ci && npm run build && cp package-lock.json node_modules/.lock-stamp

COPY package.json package-lock.json ./
RUN npm ci && cp package-lock.json node_modules/.lock-stamp

COPY . .

ENTRYPOINT ["/rails/bin/docker-entrypoint-dev"]

EXPOSE 80 3036
CMD ["./bin/rails", "server"]
