source "https://rubygems.org"

gem "rails", "~> 8.1.3", ">= 8.1.3.1"
gem "propshaft"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "json", "< 3"

gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 3.1"
gem "rack-oauth2", "~> 2.2"
gem "openid_connect", "~> 2.3"
gem "rqrcode", "~> 3.1"
gem "rotp", "~> 6.3"
gem "webauthn", "~> 3.4"
gem "fido_metadata", "~> 0.5"
gem "device_detector", "~> 1.1"
gem "graphql", "~> 2.6"
gem "premailer-rails", "~> 1.12"
gem "ruby-vips", "~> 2.2", require: false

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "solid_cache"
gem "solid_queue"

gem "thruster", require: false
gem "vite_rails"

group :development, :test do
  gem "dotenv-rails"
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
  gem "letter_opener_web", "~> 3.0"
end

group :test do
  gem "capybara"
  gem "webmock"
end
