default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      processes: <%= Masks.conf.workers || 1 %>
      threads: <%= Masks.conf.threads || 1 %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
