"masks:manage": "Modify the masks backend"
"openid": "Use your unique account identifier"
"email": "See your email address"
"nickname": "See your nickname"
"name": "See your full name"
"profile": "See your profile—including name and email"
