masks_image: ghcr.io/masksrb/masks
masks_image_tag: latest
masks_deploy_path: /srv/masks
masks_network: edge
masks_postgres_host: postgres
masks_postgres_port: 5432
masks_postgres_user: masks
masks_postgres_database: masks
masks_tenants: []
