# Customize your masks installation in this file.
#
# - https://masksrb.github.io/guides/rails
# - https://masksrb.github.io/reference/masks.yml
defaults: &defaults
  url: http://localhost:5000

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
